# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-29 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='desription',
            new_name='description',
        ),
    ]
